# Whisker SwiftLint Configuration

# ─── Excluded Paths ───────────────────────────────────
excluded:
  - .build
  - .swiftpm

# ─── Disabled Rules ───────────────────────────────────
disabled_rules:
  - todo # Allow TODO/FIXME comments during development

# ─── Rule Configuration ──────────────────────────────

# Identifier names: allow short names common in geometry, color, and loop contexts
identifier_name:
  allowed_symbols: ["_"]
  min_length:
    warning: 1
    error: 0
  max_length:
    warning: 60
    error: 80
  excluded:
    - id

# Type names: allow underscore-prefixed internal protocol markers
type_name:
  allowed_symbols: ["_"]
  min_length:
    warning: 3
    error: 0

# Line length: generous for a framework with generic signatures
line_length:
  warning: 140
  error: 200
  ignores_urls: true
  ignores_function_declarations: true